-- MySQL Script generated by MySQL Workbench
-- Tue Nov  9 21:07:52 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`telefone` (
  `idtelefone` INT NOT NULL AUTO_INCREMENT,
  `mun` INT NULL,
  `telefonecol` VARCHAR(45) NULL,
  PRIMARY KEY (`idtelefone`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `data_cadastro` VARCHAR(45) NULL,
  `indicacao` VARCHAR(45) NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`piloto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`piloto` (
  `idpiloto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `breve` VARCHAR(45) NULL,
  `data_contratacao` DATE NULL,
  `voo_idprotocolo` INT NOT NULL,
  PRIMARY KEY (`idpiloto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vendedor` (
  `idvendedor` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `desconto` VARCHAR(45) NULL,
  PRIMARY KEY (`idvendedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pessoa` (
  `idpessoa` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `rg` VARCHAR(45) NULL,
  `cpf` VARCHAR(45) NULL,
  `logadouro` VARCHAR(45) NULL,
  `num` INT(30) NULL,
  `cep` INT NULL,
  `telefone_idtelefone` INT NOT NULL,
  `cliente_idcliente` INT NOT NULL,
  `piloto_idpiloto` INT NOT NULL,
  `vendedor_idvendedor` INT NOT NULL,
  PRIMARY KEY (`idpessoa`, `nome`),
  INDEX `fk_pessoa_telefone_idx` (`telefone_idtelefone` ASC) VISIBLE,
  INDEX `fk_pessoa_cliente1_idx` (`cliente_idcliente` ASC) VISIBLE,
  INDEX `fk_pessoa_piloto1_idx` (`piloto_idpiloto` ASC) VISIBLE,
  INDEX `fk_pessoa_vendedor1_idx` (`vendedor_idvendedor` ASC) VISIBLE,
  CONSTRAINT `fk_pessoa_telefone`
    FOREIGN KEY (`telefone_idtelefone`)
    REFERENCES `mydb`.`telefone` (`idtelefone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoa_cliente1`
    FOREIGN KEY (`cliente_idcliente`)
    REFERENCES `mydb`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoa_piloto1`
    FOREIGN KEY (`piloto_idpiloto`)
    REFERENCES `mydb`.`piloto` (`idpiloto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoa_vendedor1`
    FOREIGN KEY (`vendedor_idvendedor`)
    REFERENCES `mydb`.`vendedor` (`idvendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contratos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contratos` (
  `idcontratos` INT NOT NULL AUTO_INCREMENT,
  `valor` VARCHAR(45) NULL,
  PRIMARY KEY (`idcontratos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`negociacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`negociacao` (
  `cliente_idcliente` INT NOT NULL,
  `vendedor_idvendedor` INT NOT NULL,
  `contratos_idcontratos` INT NOT NULL,
  PRIMARY KEY (`cliente_idcliente`, `vendedor_idvendedor`),
  INDEX `fk_cliente_has_vendedor_vendedor1_idx` (`vendedor_idvendedor` ASC) VISIBLE,
  INDEX `fk_cliente_has_vendedor_cliente1_idx` (`cliente_idcliente` ASC) VISIBLE,
  INDEX `fk_negociacao_contratos1_idx` (`contratos_idcontratos` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_has_vendedor_cliente1`
    FOREIGN KEY (`cliente_idcliente`)
    REFERENCES `mydb`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_has_vendedor_vendedor1`
    FOREIGN KEY (`vendedor_idvendedor`)
    REFERENCES `mydb`.`vendedor` (`idvendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_negociacao_contratos1`
    FOREIGN KEY (`contratos_idcontratos`)
    REFERENCES `mydb`.`contratos` (`idcontratos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`veiculo` (
  `idveiculo` INT NOT NULL AUTO_INCREMENT,
  `autonomia` VARCHAR(45) NULL,
  `capacidade` VARCHAR(45) NULL,
  `velocidade` VARCHAR(45) NULL,
  `n_chassi` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`idveiculo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`piloto_has_veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`piloto_has_veiculo` (
  `piloto_idpiloto` INT NOT NULL,
  `veiculo_idveiculo` INT NOT NULL,
  PRIMARY KEY (`piloto_idpiloto`, `veiculo_idveiculo`),
  INDEX `fk_piloto_has_veiculo_veiculo1_idx` (`veiculo_idveiculo` ASC) VISIBLE,
  INDEX `fk_piloto_has_veiculo_piloto1_idx` (`piloto_idpiloto` ASC) VISIBLE,
  CONSTRAINT `fk_piloto_has_veiculo_piloto1`
    FOREIGN KEY (`piloto_idpiloto`)
    REFERENCES `mydb`.`piloto` (`idpiloto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_piloto_has_veiculo_veiculo1`
    FOREIGN KEY (`veiculo_idveiculo`)
    REFERENCES `mydb`.`veiculo` (`idveiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
